INSERT INTO products (name, price, can_be_returned) VALUES ('chair', 44.00, 'f') "STEP 1"
INSERT INTO products(name, price, can_be_returned) VALUES ('stool',25.99, 't')  "STEP 2"
INSERT INTO products(name, price, can_be_returned) VALUES ('table',124, 'f') "STEP 3"
SELECT * FROM products; "STEP 4"
SELECT name FROM products; "STEP 5"
SELECT name, price FROM products; "STEP 6"
INSERT INTO products(name, price, can_be_returned) VALUES ('xbox', 500.00 't') "STEP 7"
SELECT * FROM products WHERE can_be_returned "STEP 8"
SELECT * FROM products WHERE price < 44.00 "STEP 9"
SELECT * FROM products WHERE price BETWEEN 22.50 AND 99.99 "STEP 10"
UPDATE products SET price = price - 20 "STEP 11"
DELETE FROM products WHERE price < 25 "STEP 12"
UPDATE products SET price = price + 20  "STEP 13"
UPDATE products SET can_be_returned = 't'